[project]
name = "funcnodes-nodebuilder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "funcnodes>=0.5.35",
    "funcnodes-pyodide>=0.1.2",
]
